package ro.bid4.backend.orders.domain;

public enum OrderEvent {
  OFFER_ACCEPTED,
  DELIVERY_CHOSEN,
  PAYMENT_HELD,
  LABEL_READY,
  SHIPPED,
  DELIVERED,
  RELEASED,
  DISPUTE_OPENED,
  DISPUTE_RESOLVED,
  CANCELLED
}
