-- bid4 — core identity, authentication, and the two gates that unlock bidding.
--
-- Conventions every migration in this project follows:
--   * uuid primary keys generated by the database, so one id never reveals the
--     next and an enumeration attack has nothing to walk;
--   * money is bigint bani (RON minor units), never numeric or float, matching
--     lib/money.ts on the frontend and the fee service here;
--   * every instant is timestamptz, stored UTC;
--   * enumerations are varchar + CHECK rather than a native pg enum: a CHECK
--     widens in a later migration without an exclusive lock. The allowed values
--     mirror the TypeScript unions in frontend/src/lib/types exactly;
--   * fixed-width values are varchar with a CHECK on the shape, never char(n).
--     Postgres blank-pads char(n) and gains nothing for it, and the padding
--     reads back as a column type Hibernate refuses to match.

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $fn$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    email                   varchar(254) NOT NULL,
    password_hash           varchar(120) NOT NULL,
    display_name            varchar(60)  NOT NULL,
    username                varchar(40)  NOT NULL,

    role                    varchar(16)  NOT NULL DEFAULT 'USER',
    account_type            varchar(16)  NOT NULL DEFAULT 'INDIVIDUAL',
    status                  varchar(16)  NOT NULL DEFAULT 'ACTIVE',

    org_legal_name          varchar(160),
    org_registration_number varchar(32),

    avatar_url              varchar(512),
    bio                     varchar(1000) NOT NULL DEFAULT '',
    city                    varchar(80),

    stripe_ready            boolean      NOT NULL DEFAULT false,
    stripe_account_id       varchar(64),

    rating                  numeric(2,1) NOT NULL DEFAULT 0,
    rating_count            integer      NOT NULL DEFAULT 0,
    total_raised            bigint       NOT NULL DEFAULT 0,

    -- Brute-force state. The live per-IP counter lives in Redis; this is the
    -- durable per-account half, so an attempt spread over many IPs still trips.
    failed_login_count      integer      NOT NULL DEFAULT 0,
    locked_until            timestamptz,
    last_login_at           timestamptz,
    password_changed_at     timestamptz  NOT NULL DEFAULT now(),
    email_verified_at       timestamptz,
    -- Bumped to invalidate every access token already issued to this user.
    token_version           integer      NOT NULL DEFAULT 0,

    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT users_role_valid         CHECK (role IN ('USER', 'OPERATOR', 'ADMIN')),
    CONSTRAINT users_account_type_valid CHECK (account_type IN ('INDIVIDUAL', 'ORGANIZATION')),
    CONSTRAINT users_status_valid       CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT users_email_lower        CHECK (email = lower(email)),
    CONSTRAINT users_email_shape        CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT users_username_shape     CHECK (username ~ '^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]$'),
    CONSTRAINT users_display_name_len   CHECK (char_length(display_name) BETWEEN 2 AND 60),
    CONSTRAINT users_rating_range       CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT users_counters_positive  CHECK (rating_count >= 0 AND total_raised >= 0
                                               AND failed_login_count >= 0)
);

CREATE UNIQUE INDEX users_email_key    ON users (email);
CREATE UNIQUE INDEX users_username_key ON users (username);
CREATE INDEX users_role_status_idx     ON users (role, status);
CREATE INDEX users_created_at_idx      ON users (created_at DESC);

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- refresh_tokens — rotating, hashed, reuse-detecting
-- ---------------------------------------------------------------------------

CREATE TABLE refresh_tokens (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- SHA-256 of the token. The token is shown to its owner once and is never
    -- recoverable from here, so a dump of this table grants nothing.
    token_hash    varchar(64) NOT NULL,
    issued_at     timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL,
    revoked_at    timestamptz,
    -- Set when this token was exchanged. A refresh presented against an already
    -- rotated row means the token leaked, and the whole chain is revoked.
    rotated_to    uuid REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    user_agent    varchar(255),
    ip            inet,

    CONSTRAINT refresh_tokens_hash_shape CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT refresh_tokens_lifespan   CHECK (expires_at > issued_at)
);

CREATE UNIQUE INDEX refresh_tokens_hash_key ON refresh_tokens (token_hash);
CREATE INDEX refresh_tokens_user_idx        ON refresh_tokens (user_id, expires_at DESC);
CREATE INDEX refresh_tokens_expiry_idx      ON refresh_tokens (expires_at)
    WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- login_attempts — the audit half of brute-force defence
-- ---------------------------------------------------------------------------

CREATE TABLE login_attempts (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- Not a foreign key on purpose: the interesting rows are attempts against
    -- addresses that do not exist.
    email_attempted varchar(254) NOT NULL,
    user_id         uuid REFERENCES users (id) ON DELETE SET NULL,
    ip              inet NOT NULL,
    user_agent      varchar(255),
    successful      boolean NOT NULL,
    failure_reason  varchar(32),
    attempted_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT login_attempts_email_lower CHECK (email_attempted = lower(email_attempted))
);

CREATE INDEX login_attempts_email_idx ON login_attempts (email_attempted, attempted_at DESC);
CREATE INDEX login_attempts_ip_idx    ON login_attempts (ip, attempted_at DESC);

-- ---------------------------------------------------------------------------
-- delivery_methods — one half of the gate that unlocks bidding
-- ---------------------------------------------------------------------------

CREATE TABLE delivery_methods (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type              varchar(16) NOT NULL,
    label             varchar(80) NOT NULL,

    easybox_locker_id varchar(40),
    locker_name       varchar(160),
    locker_address    varchar(255),

    recipient_name    varchar(120),
    street            varchar(255),
    city              varchar(80),
    county            varchar(40),
    postal_code       varchar(12),
    address_details   varchar(255),

    phone             varchar(20) NOT NULL,
    is_default        boolean NOT NULL DEFAULT false,

    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT delivery_methods_type_valid CHECK (type IN ('EASYBOX', 'HOME_COURIER')),
    -- Each type carries the fields its label needs, and only those.
    CONSTRAINT delivery_methods_shape CHECK (
        (type = 'EASYBOX' AND easybox_locker_id IS NOT NULL AND locker_name IS NOT NULL)
        OR (type = 'HOME_COURIER' AND recipient_name IS NOT NULL AND street IS NOT NULL
            AND city IS NOT NULL AND county IS NOT NULL AND postal_code IS NOT NULL)
    ),
    CONSTRAINT delivery_methods_phone_shape CHECK (phone ~ '^\+?[0-9]{9,15}$')
);

CREATE INDEX delivery_methods_user_idx ON delivery_methods (user_id);
-- At most one default per user, enforced here rather than by whoever remembers
-- to clear the previous one first.
CREATE UNIQUE INDEX delivery_methods_one_default ON delivery_methods (user_id)
    WHERE is_default;

CREATE TRIGGER delivery_methods_set_updated_at
    BEFORE UPDATE ON delivery_methods
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE users
    ADD COLUMN default_delivery_method_id uuid
        REFERENCES delivery_methods (id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- payment_methods — the other half of the gate
-- ---------------------------------------------------------------------------

-- No column here can hold a card number. What is stored is what Stripe safely
-- exposes about a saved PaymentMethod, plus its opaque id.
CREATE TABLE payment_methods (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider           varchar(16) NOT NULL DEFAULT 'STRIPE',
    provider_method_id varchar(64) NOT NULL,

    brand              varchar(16)  NOT NULL,
    last4              varchar(4)   NOT NULL,
    exp_month          smallint     NOT NULL,
    exp_year           smallint     NOT NULL,
    holder_name        varchar(120) NOT NULL,
    is_default         boolean      NOT NULL DEFAULT false,

    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT payment_methods_provider_valid CHECK (provider IN ('STRIPE')),
    CONSTRAINT payment_methods_brand_valid    CHECK (brand IN ('VISA', 'MASTERCARD', 'AMEX', 'OTHER')),
    CONSTRAINT payment_methods_last4_shape    CHECK (last4 ~ '^[0-9]{4}$'),
    CONSTRAINT payment_methods_exp_month      CHECK (exp_month BETWEEN 1 AND 12),
    CONSTRAINT payment_methods_exp_year       CHECK (exp_year BETWEEN 2020 AND 2099)
);

CREATE UNIQUE INDEX payment_methods_provider_key ON payment_methods (provider, provider_method_id);
CREATE INDEX payment_methods_user_idx            ON payment_methods (user_id);
CREATE UNIQUE INDEX payment_methods_one_default  ON payment_methods (user_id)
    WHERE is_default;

CREATE TRIGGER payment_methods_set_updated_at
    BEFORE UPDATE ON payment_methods
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- stored_files — the index over MinIO
-- ---------------------------------------------------------------------------

-- Nothing in the application builds an object key by hand: it reads the one on
-- this row. A caller therefore cannot reach an object by guessing a key, and
-- cannot reach one it does not own without failing the check on owner_id.
CREATE TABLE stored_files (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    bucket          varchar(63)  NOT NULL,
    object_key      varchar(512) NOT NULL,
    visibility      varchar(16)  NOT NULL,

    original_name   varchar(255) NOT NULL,
    content_type    varchar(120) NOT NULL,
    size_bytes      bigint       NOT NULL,
    checksum_sha256 varchar(64)  NOT NULL,

    owner_id        uuid REFERENCES users (id) ON DELETE SET NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT stored_files_visibility_valid CHECK (visibility IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT stored_files_size_sane        CHECK (size_bytes > 0 AND size_bytes <= 8 * 1024 * 1024),
    CONSTRAINT stored_files_checksum_shape   CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),
    -- The allow-list is repeated in the upload service; this is the backstop.
    CONSTRAINT stored_files_content_type_allowed CHECK (
        content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')
    )
);

CREATE UNIQUE INDEX stored_files_object_key ON stored_files (bucket, object_key);
CREATE INDEX stored_files_owner_idx         ON stored_files (owner_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    at          timestamptz NOT NULL DEFAULT now(),
    actor_id    uuid REFERENCES users (id) ON DELETE SET NULL,
    actor_ip    inet,
    action      varchar(64) NOT NULL,
    entity_type varchar(40),
    entity_id   uuid,
    detail      jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX audit_log_at_idx     ON audit_log (at DESC);
CREATE INDEX audit_log_actor_idx  ON audit_log (actor_id, at DESC);
CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id, at DESC);
