bid4:
  cookies:
    require-secure: false
  dev:
    seed: true

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{requestId:-boot}]){faint} %clr(%-38.38logger{0}){cyan} %clr(:){faint} %m%n%wEx"

  level:
    root: INFO

    ro.bid4.backend: DEBUG

    ro.bid4.backend.http: DEBUG

    org.hibernate.SQL: DEBUG

    org.flywaydb.core.internal.command: DEBUG

    org.springframework.security.web.FilterChainProxy: DEBUG
